name: open_graph_parser
author: "Patrick Voß <patrick.voss1808@gmail.com>"
homepage: https://github.com/Patte1808/open_graph_parser
description: An open graph parser for Dart.
version: 0.0.1
environment:
    sdk: ">=2.0.0 <2.2.0"
dependencies:
  http: ^0.12.0
  html: ^0.13.3+3